<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>ArgaNestIconHandler</RootNamespace>
    <AssemblyName>ArgaNestIconHandler</AssemblyName>
    <PlatformTarget>x64</PlatformTarget>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin\</OutputPath>
    <ComVisible>true</ComVisible>
    <LangVersion>latest</LangVersion>
    <EnableComHosting>false</EnableComHosting>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SharpShell" Version="2.7.2" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.IO.Compression" />
  </ItemGroup>
</Project>
